### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by stmoon** [jongchyisu/mvcnn_pytorch#2]
Hello,

I have tried to train the system.  While training, I found some error in the ImgDataset.py like below
```
im = Image.open(self.filepaths[idx]).convert('RGB')
```

I used cuda 9.2.148 at ubuntu 18.04

Thanks in advance

```
epoch 1, step 25: train_loss 2.269; train_acc 0.406
epoch 1, step 26: train_loss 2.170; train_acc 0.438
Traceback (most recent call last):
  File "train_mvcnn.py", line 61, in <module>
    trainer.train(30)
  File "/home/stmoon/Test/mvcnn_pytorch/tools/Trainer.py", line 50, in train
    for i, data in enumerate(self.train_loader):
  File "/home/stmoon/Test/mvcnn_pytorch/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/stmoon/Test/mvcnn_pytorch/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/stmoon/Test/mvcnn_pytorch/tools/ImgDataset.py", line 130, in __getitem__
    im = Image.open(self.filepaths[idx]).convert('RGB')
  File "/home/stmoon/Test/mvcnn_pytorch/env/lib/python3.6/site-packages/PIL/Image.py", line 915, in convert
    self.load()
  File "/home/stmoon/Test/mvcnn_pytorch/env/lib/python3.6/site-packages/PIL/ImageFile.py", line 250, in load
    self.load_end()
  File "/home/stmoon/Test/mvcnn_pytorch/env/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 677, in load_end
    self.png.call(cid, pos, length)
  File "/home/stmoon/Test/mvcnn_pytorch/env/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 140, in call
    return getattr(self, "chunk_" + cid.decode('ascii'))(pos, length)
  File "/home/stmoon/Test/mvcnn_pytorch/env/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 356, in chunk_IDAT
    raise EOFError
EOFError
```

**Comment by jongchyisu** [comment]
Can you find out which file path causes this error?

**Comment by stmoon** [comment]
It is different then... 

I solve this problem like this. However, I'm not sure why it is working..


```
 78             im = Image.open(self.filepaths[idx*self.num_views+i])
 79             try :
 80                 im = im.convert('RGB')
 81             except EOFError :
 82                 im = im.convert('RGB')
```
