### ISSUE TITLE
ValueError: 'modelnet40_images_new_12x' is not in list

### ISSUE THREAD

**Issue by libeike** [jongchyisu/mvcnn_pytorch#29]
Does anyone have this problem? How do you solve this?

` E:\LBKpy\mvcnn_pytorch-master>python train_mvcnn.py -name mvcnn -num_models 1000 -weight_decay 0.001 -num_views 12 -cnn_name vgg11
E:\Anaconda\envs\multiview\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'E:\Anaconda\envs\multiview\Lib\site-packages\torchvision\image.pyd' (or one of its d
ependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
WARNING: summary folder already exists!! It will be overwritten!!
WARNING: summary folder already exists!! It will be overwritten!!
num_train_files: 118116
num_val_files: 29616
Traceback (most recent call last):
  File "train_mvcnn.py", line 61, in <module>
    trainer.train(30)
  File "E:\LBKpy\mvcnn_pytorch-master\tools\Trainer.py", line 50, in train
    for i, data in enumerate(self.train_loader):
  File "E:\Anaconda\envs\multiview\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "E:\Anaconda\envs\multiview\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\Anaconda\envs\multiview\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Anaconda\envs\multiview\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\LBKpy\mvcnn_pytorch-master\tools\ImgDataset.py", line 127, in __getitem__
    class_id = self.classnames.index(class_name)
ValueError: 'modelnet40_images_new_12x' is not in list
`

**Comment by zhangdongwei1998** [comment]
I encountered the same problem, have you solve this it? Thanks.

**Comment by zhangdongwei1998** [comment]
I encountered the same problem, have you solve it? Thanks

**Comment by YY-MyWorld** [comment]
Did you solve it please?I got the same error

**Comment by 1987553369** [comment]
ImgDataset.py 127行，class_name=path.split('/')[-3]改成 class_name=path.split('/')[-2]
