### ISSUE TITLE
how to directly run stage2 mvcnn

### ISSUE THREAD

**Issue by zhangdongwei1998** [jongchyisu/mvcnn_pytorch#31]
Thanks for your great work, I wonder how to directly run stage2 mvcnn without run stage1 first. I would appreciate if you could give some advice.

**Comment by YY-MyWorld** [comment]
Traceback (most recent call last):
  File "train_mvcnn.py", line 79, in <module>
    trainer.train(1)
  File "/home/wanghuijuan1/MVCNN/mvcnn_pytorch-master/tools/Trainer.py", line 50, in train
    for i, data in enumerate(self.train_loader):
  File "/home/wanghuijuan1/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/wanghuijuan1/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/wanghuijuan1/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wanghuijuan1/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wanghuijuan1/MVCNN/mvcnn_pytorch-master/tools/ImgDataset.py", line 76, in __getitem__
    class_id = self.classnames.index(class_name)
ValueError: 'train' is not in list
stage2 mvcnn unable to execute，This problem occurred, did you have this problem? How did you solve it, thanks a lot
