### ISSUE TITLE
ValueError: 'modelnet40_images_new_12x' is not in list

### ISSUE THREAD

**Issue by YY-MyWorld** [jongchyisu/mvcnn_pytorch#32]
D:\python\anaconda\python.exe D:/_多媒体检索/mvcnn_pytorch-master/train_mvcnn.py
WARNING: summary folder already exists!! It will be overwritten!!
WARNING: summary folder already exists!! It will be overwritten!!
num_train_files: 118116
num_val_files: 29616
Traceback (most recent call last):
  File "D:/_多媒体检索/mvcnn_pytorch-master/train_mvcnn.py", line 61, in <module>
    trainer.train(30)
  File "D:\_多媒体检索\mvcnn_pytorch-master\tools\Trainer.py", line 50, in train
    for i, data in enumerate(self.train_loader):
  File "D:\python\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "D:\python\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\python\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\python\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\_多媒体检索\mvcnn_pytorch-master\tools\ImgDataset.py", line 127, in __getitem__
    class_id = self.classnames.index(class_name)
ValueError: 'modelnet40_images_new_12x' is not in list

Process finished with exit code 1

**Comment by liuzh594** [comment]
The code should run under Linux, maybe you are running it under Windows. You need to change `class_name = path.split('/')[-3]` to `class_name = path.split('/')[-2]` in `__getitem__` method under ImgDataset.py.

**Comment by YY-MyWorld** [comment]
Excuse me again, I try to modify in windows environment&nbsp;class_name = path.split('/')[-3]&nbsp;to&nbsp;class_name = path.split('/')[-2]&nbsp;。But the problem still exists, does it have to be run under linux?Looking forward to your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月19日(星期二) 上午8:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jongchyisu/mvcnn_pytorch] ValueError: &#39;modelnet40_images_new_12x&#39; is not in list (Issue #32)





 
The code should run under Linux, maybe you are running it under Windows. You need to change class_name = path.split('/')[-3] to class_name = path.split('/')[-2] in __getitem__ method under ImgDataset.py.
